name: Run Tests with Pytest

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html requests python-dotenv

      - name: Verify installed packages
        run: pip list

      - name: Set environment variable
        env:
          RUTA: ${{ secrets.RUTA }}

      - name: Run Pytest with HTML Report
        run: |
          pytest --maxfail=1 --disable-warnings -q --html=report.html --self-contained-html

      - name: Upload HTML Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
